// JavaScript Document
Ext.ux.addCustomerForm=Ext.extend(Ext.FormPanel,{
		initComponent:function(){
			this.frame=true,
			this.autoHeight=true,
			this.buttonAlign='center',
			this.creatItems();
			this.creatButtons();
			Ext.ux.addCustomerForm.superclass.initComponent.call(this);
		},
		creatItems:function(){
			var cost={};
			if(!this.customer.id){
				cost=new Ext.form.FieldSet({title:'资费信息',autoHeight : true,width:800,
					layout:'column',items:[
						{columnWidth:.5,layout:'form',defaultType:'textfield',
							items:[{xtype:'combo',
									store:new Ext.data.SimpleStore({fields:["id","key_type"],data:this.pay_cycle}),
									valueField:"id",
									displayField:"key_type",mode:'local',
									width:200,
									editable:false,
									forceSelection:true,
									triggerAction:'all',
									hiddenName:'pay_cycle',
									name:'pay_cycle',
									value:this.customer.pay_cycle,
									id:'pay_cycle',
									allowBlank:false,
									fieldLabel:'付费周期'},{xtype:'combo',
									store:new Ext.data.SimpleStore({fields:["id","key_type"],data:this.pay_type}),
									valueField:"id",
									displayField:"key_type",mode:'local',
									width:200,
									editable:false,
									forceSelection:true,
									triggerAction:'all',
									hiddenName:'pay_type',
									name:'pay_type',
									id:'pay_type',
									allowBlank:false,
									fieldLabel:'付款方式'}
							]},
						{columnWidth:.5,layout:'form',defaultType:'textfield', 
							items:[{fieldLabel:'资费',
								id:'price', 
								width:200,
								allowBlank:false,
								xtype:'numberfield',
								decimalPrecision:4,
								allowDecimals:true,
								value:this.customer.price
								},{fieldLabel:'签约付款',
								id:'paid', 
								width:200,
								allowBlank:false,
								xtype:'numberfield',
								decimalPrecision:4,
								allowDecimals:true
								}]}]});
			}else{
				cost=new Ext.form.FieldSet({title:'资费信息',autoHeight : true,width:800,
					layout:'column',items:[
						{columnWidth:.5,layout:'form',defaultType:'textfield',
							items:[{xtype:'combo',
									store:new Ext.data.SimpleStore({fields:["id","key_type"],data:this.pay_cycle}),
									valueField:"id",
									displayField:"key_type",mode:'local',
									width:200,
									editable:false,
									forceSelection:true,
									triggerAction:'all',
									hiddenName:'pay_cycle',
									name:'pay_cycle',
									value:this.customer.pay_cycle,
									id:'pay_cycle',
									allowBlank:false,
									fieldLabel:'付费周期'}
							]},
						{columnWidth:.5,layout:'form',defaultType:'textfield', 
							items:[{fieldLabel:'资费',
								id:'price', 
								width:200,
								allowBlank:false,
								value:this.customer.price
								}]}]});
			}
			this.items=[new Ext.form.FieldSet({title:'基本信息',autoHeight : true,width:800,
				layout:'column',items:[
					{columnWidth:.5,layout:'form',defaultType:'textfield',
						items:[{xtype:'hidden',id:'id',value:this.customer.id},
								{fieldLabel:'企业账号',
								id:'account', 
								width:200,
								allowBlank:false,
								value:this.customer.account
								},{fieldLabel:'联系人',
								id:'contact', 
								width:200,
								allowBlank:false,
								value:this.customer.contact
								},{fieldLabel:'电话',
								id:'tel', 
								width:200,
								allowBlank:false,
								value:this.customer.tel
								},{fieldLabel:'地址',
								id:'address', 
								width:200,
								value:this.customer.address
								},{fieldLabel:'QQ',
								id:'qq', 
								width:200,
								xtype:'numberfield',
								decimalPrecision:0,
								allowDecimals:true,
								value:this.customer.qq
								},{fieldLabel:'Skype',
								id:'skype', 
								width:200,
								value:this.customer.skype
								}
						]},
					{columnWidth:.5,layout:'form',defaultType:'textfield', 
						items:[{fieldLabel:'企业名称',
								id:'name', 
								width:200,
								allowBlank:false,
								value:this.customer.name
								},{fieldLabel:'签约时间',
								allowBlank:false,
								width:200,
								maxValue:new Date(),
								xtype:'datefield',
								format:'Y-m-d',
								id:'sign_time',
								value:this.customer.sign_time
								},{fieldLabel:'销售人员',
								id:'sale_user', 
								width:200,
								value:this.customer.sale_user
								},{fieldLabel:'邮编',
								id:'zip', 
								width:200,
								value:this.customer.zip
								},{fieldLabel:'Email',
								id:'Email', 
								width:200,
								vtype:"email",//email格式验证
               					vtypeText:"不是有效的邮箱地址",
								value:this.customer.Email
								}
						]}]}),
			cost,
			{fieldLabel:'备注',id:'comment',name:'comment',width:700,height:50,value:this.customer.comment,xtype:'textarea'}]
		},
		creatButtons:function(){
			this.buttons=[{text:'保存',type:'submit',handler:this.formsave.createDelegate(this)},
						  {text:'重置',handler:this.formreset.createDelegate(this)}];},
		formsave:function(){
			if(this.getForm().isValid()){
				this.getForm().submit({
					url:'index.php?model=customer&action=save',
					waitMsg:'正在更新客户资料',
					params:'',
					method:'post',success:function(form,action){
						if(action.result.success){
							Ext.example.msg('MSG','新增客户成功');
							window.location.href='index.php?model=customer&action=add&id='+action.result.msg;
						}else{
							Ext.Msg.alert('新增客户失败',action.result.msg);
						}
					},
					failure:function(form,action){
						Ext.Msg.alert('新增客户失败',action.result.msg);
					}});
			}else{
				Ext.example.msg('ERROR','请正确完成表单内容');
			}
		},
		formreset:function(){
			this.form.reset();
		}
});