// JavaScript Document
Ext.ux.payForm=Ext.extend(Ext.FormPanel,{
		initComponent:function(){
			this.frame=true,
			this.autoHeight=true,
			this.buttonAlign='center',
			this.creatItems();
			this.creatButtons();
			Ext.ux.payForm.superclass.initComponent.call(this);
		},
		creatItems:function(){
			this.items=[{layout:'form',defaultType:'textfield',
						items:[{xtype:'hidden',id:'customer_id',value:this.customer.id},
								{fieldLabel:'企业账号',
								id:'account', 
								width:200,
								disabled:true,
								value:this.customer.account
								},{fieldLabel:'企业名称',
								id:'name',
								width:200, 
								disabled:true,
								value:this.customer.name
								},{fieldLabel:'联系人',
								id:'contact', 
								width:200,
								disabled:true,
								value:this.customer.contact
								},{fieldLabel:'电话',
								id:'tel', 
								disabled:true,
								width:200,
								value:this.customer.tel
								},{fieldLabel:'付费周期',
								id:'pay_cycle_name', 
								disabled:true,
								width:200,
								value:this.customer.pay_cycle_name,
								},{xtype:'hidden',id:'pay_cycle',value:this.customer.pay_cycle
								},{fieldLabel:'资费',
								id:'price', 
								disabled:true,
								width:200,
								value:this.customer.price
								},{fieldLabel:'上次付费时间',
								id:'last_pay_time_format', 
								width:200,
								disabled:true,
								value:this.customer.last_pay_time_format
								},{xtype:'hidden',id:'last_pay_time',value:this.customer.last_pay_time
								},{fieldLabel:'余额',
								id:'remain', 
								disabled:true,
								width:200,
								value:this.customer.remain
								},{fieldLabel:'应付金额',
								id:'payable', 
								disabled:true,
								width:200,
								value:this.customer.payable
								},{xtype:'combo',
								store:new Ext.data.SimpleStore({fields:["id","key_type"],data:this.pay_type}),
								valueField:"id",
								displayField:"key_type",mode:'local',
								width:200,
								editable:false,
								forceSelection:true,
								triggerAction:'all',
								hiddenName:'pay_type',
								name:'pay_type',
								id:'pay_type',
								allowBlank:false,
								fieldLabel:'付款方式'
								},{fieldLabel:'付款金额',
								id:'paid', 
								width:200,
								allowBlank:false,
								xtype:'numberfield',
								decimalPrecision:4,
								allowDecimals:true
								},{fieldLabel:'付款人',
								id:'pay_user', 
								width:200,
								name:'pay_user'
								},{fieldLabel:'备注',
								id:'comment',
								name:'comment',
								width:200,height:50,xtype:'textarea'}]}]
		},
		creatButtons:function(){
			this.buttons=[{text:'付款',type:'submit',handler:this.formsave.createDelegate(this)},
						  {text:'重置',handler:this.formreset.createDelegate(this)}];},
		formsave:function(){
			if(Ext.fly('paid').dom.value<=0){
				Ext.example.msg('ERROR','请正确完成表单内容,付款金额必须大于0');
			}else{
				if(this.getForm().isValid()){
					this.getForm().submit({
						url:'index.php?model=customer&action=pay',
						waitMsg:'正在提交付款',
						params:'',
						method:'post',success:function(form,action){
							if(action.result.success){
								Ext.example.msg('MSG','付款成功');
							}else{
								Ext.Msg.alert('付款失败',action.result.msg);
							}
						},
						failure:function(form,action){
							Ext.Msg.alert('付款失败',action.result.msg);
						}});
				}else{
					Ext.example.msg('ERROR','请正确完成表单内容');
				}
			}
		},
		formreset:function(){
			this.form.reset();
		}
});