<title>语言编码对照表</title>
国家名称：
        英语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：en<br/>国家名称：
        —
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：separator<br/>国家名称：
        阿尔巴尼亚语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：sq<br/>国家名称：
        阿拉伯语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：ar<br/>国家名称：
        阿塞拜疆语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：az<br/>国家名称：
        爱尔兰语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：ga<br/>国家名称：
        爱沙尼亚语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：et<br/>国家名称：
        巴斯克语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：eu<br/>国家名称：
        白俄罗斯语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：be<br/>国家名称：
        保加利亚语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：bg<br/>国家名称：
        冰岛语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：is<br/>国家名称：
        波兰语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：pl<br/>国家名称：
        波斯尼亚语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：bs<br/>国家名称：
        波斯语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：fa<br/>国家名称：
        布尔语(南非荷兰语)
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：af<br/>国家名称：
        丹麦语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：da<br/>国家名称：
        德语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：de<br/>国家名称：
        俄语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：ru<br/>国家名称：
        法语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：fr<br/>国家名称：
        菲律宾语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：tl<br/>国家名称：
        芬兰语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：fi<br/>国家名称：
        高棉语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：km<br/>国家名称：
        格鲁吉亚语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：ka<br/>国家名称：
        古吉拉特语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：gu<br/>国家名称：
        海地克里奥尔语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：ht<br/>国家名称：
        韩语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：ko<br/>国家名称：
        荷兰语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：nl<br/>国家名称：
        加利西亚语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：gl<br/>国家名称：
        加泰罗尼亚语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：ca<br/>国家名称：
        捷克语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：cs<br/>国家名称：
        卡纳达语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：kn<br/>国家名称：
        克罗地亚语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：hr<br/>国家名称：
        拉丁语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：la<br/>国家名称：
        拉脱维亚语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：lv<br/>国家名称：
        老挝语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：lo<br/>国家名称：
        立陶宛语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：lt<br/>国家名称：
        罗马尼亚语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：ro<br/>国家名称：
        马耳他语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：mt<br/>国家名称：
        马拉地语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：mr<br/>国家名称：
        马来语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：ms<br/>国家名称：
        马其顿语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：mk<br/>国家名称：
        孟加拉语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：bn<br/>国家名称：
        苗语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：hmn<br/>国家名称：
        挪威语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：no<br/>国家名称：
        葡萄牙语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：pt<br/>国家名称：
        日语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：ja<br/>国家名称：
        瑞典语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：sv<br/>国家名称：
        塞尔维亚语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：sr<br/>国家名称：
        世界语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：eo<br/>国家名称：
        斯洛伐克语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：sk<br/>国家名称：
        斯洛文尼亚语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：sl<br/>国家名称：
        斯瓦希里语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：sw<br/>国家名称：
        宿务语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：ceb<br/>国家名称：
        泰卢固语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：te<br/>国家名称：
        泰米尔语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：ta<br/>国家名称：
        泰语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：th<br/>国家名称：
        土耳其语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：tr<br/>国家名称：
        威尔士语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：cy<br/>国家名称：
        乌尔都语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：ur<br/>国家名称：
        乌克兰语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：uk<br/>国家名称：
        希伯来语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：iw<br/>国家名称：
        希腊语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：el<br/>国家名称：
        西班牙语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：es<br/>国家名称：
        匈牙利语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：hu<br/>国家名称：
        亚美尼亚语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：hy<br/>国家名称：
        意大利语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：it<br/>国家名称：
        意第绪语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：yi<br/>国家名称：
        印地语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：hi<br/>国家名称：
        印尼语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：id<br/>国家名称：
        印尼爪哇语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：jw<br/>国家名称：
        英语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：en<br/>国家名称：
        越南语
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：vi<br/>国家名称：
        中文(繁体)
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：zh-TW<br/>国家名称：
        中文(简体)
    &nbsp;&nbsp;&nbsp;&nbsp;国家代码：zh-CN<br/>
