<?php
    $AWS_ACCESS_KEY_ID = 'AKIAJJJBHFKG5OUKBCSA';
    $AWS_SECRET_ACCESS_KEY ='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';  
    $APPLICATION_NAME ='cpowersoft';
    $APPLICATION_VERSION ='2011-01-01';
    //0862-0048-5794  FR
?>